services:
  - type: web
    name: almacenhv
    runtime: docker
    repo: https://github.com/Omar666-stack/ALMACENHV.git
    plan: free
    region: ohio
    branch: master
    buildCommand: docker build -t web .
    startCommand: docker run -p $PORT:$PORT web