services:
  - type: web
    name: almacenhv
    env: docker
    plan: free
    buildCommand: docker build -t app .
    startCommand: docker run -p $PORT:$PORT app
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        sync: false