services:
  - type: web
    name: almacenhv
    runtime: docker
    repo: https://github.com/Omar666-stack/ALMACENHV.git
    region: ohio
    plan: free
    branch: master
    rootDir: ALMACENHV
    buildCommand: docker build -f ALMACENHV/Dockerfile -t almacenhv .
    startCommand: docker run -p $PORT:$PORT almacenhv
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 10000
      - key: TZ
        value: America/Lima
