services:
  - type: web
    name: almacenhv
    runtime: docker
    repo: https://github.com/Omar666-stack/ALMACENHV.git
    branch: master
    plan: free
    buildCommand: docker build -t web .
    startCommand: docker run -p $PORT:$PORT web
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production